name: audiobook
description: "audiobook projects"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  get_it: ^7.6.7
  injectable: ^2.3.5
  injectable_generator: ^2.5.1
  equatable: ^2.0.5
  auto_route: ^7.9.0
  auto_route_generator: ^7.3.2
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  easy_localization: ^3.0.5
  easy_localization_loader: ^2.0.1
  easy_localization_generator: ^0.3.2
  dio: ^5.4.1
  logger: ^2.1.0
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.8
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10+1
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/app_logo.png"

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf

  uses-material-design: true
  assets:
    - assets/localization/
    - assets/images/

flutter_gen:
  output: lib/core/gen/assets/
  integrations:
    flutter_svg: true

